package com.gestioncaravana.application.model;

public record WagonImprovementCatalogItemView(
    String code,
    String name,
    String category,
    String costExpression,
    Integer hitPointsBonus,
    Double hitPointsMultiplier,
    Integer hardnessBonus,
    Double hardnessMultiplier,
    String propulsionEffect,
    Integer travelerCapacityBonus,
    Double travelerCapacityMultiplier,
    Integer travelerCapacityMinimumIncrement,
    Integer travelerCapacityOverride,
    Integer cargoCapacityBonus,
    Double cargoCapacityMultiplier,
    Integer cargoCapacityMinimumIncrement,
    Integer cargoCapacityOverride,
    Integer consumptionBonus,
    int maxPerWagon,
    boolean repeatable,
    String requiredBasePropulsionFragment,
    int ownedCount,
    boolean available,
    String blockedReason,
    String specialBenefit,
    String description,
    String notes) {}
