spring:
  application:
    name: gestion-caravana
  main:
    banner-mode: off

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

server:
  error:
    include-message: never
