package com.gestioncaravana.domain;

import java.util.List;
import java.util.Optional;

public final class CaravanBeastCatalog {

  private static final List<CaravanBeastCatalogItem> BEASTS = List.of(
      new CaravanBeastCatalogItem(
          "caballo-ligero",
          "Caballo ligero",
          75,
          110,
          "G",
          3,
          50,
          0,
          true,
          "Ninguno",
          "Caballo ligero común para tiro y montura.",
          null),
      new CaravanBeastCatalogItem(
          "caballo-pesado",
          "Caballo pesado",
          200,
          300,
          "G",
          5,
          50,
          0,
          true,
          "Ninguno",
          "Caballo robusto y fuerte, ideal para tiro exigente.",
          null),
      new CaravanBeastCatalogItem(
          "poni",
          "Poni",
          30,
          45,
          "M",
          2,
          40,
          0,
          true,
          "Ninguno",
          "Animal pequeño y versátil usado con frecuencia para tiro ligero.",
          null),
      new CaravanBeastCatalogItem(
          "caballo-yakuto",
          "Caballo yakuto",
          400,
          600,
          "G",
          5,
          50,
          2,
          true,
          "Adaptado al frío",
          "Caballo adaptado a climas fríos.",
          null),
      new CaravanBeastCatalogItem(
          "caballo-pottoka",
          "Caballo pottoka",
          60,
          90,
          "M",
          2,
          40,
          1,
          true,
          "Adaptado al frío",
          "Caballo ligero y resistente, adecuado para climas fríos.",
          null),
      new CaravanBeastCatalogItem(
          "caballo-shire",
          "Caballo shire",
          400,
          600,
          "G",
          7,
          40,
          0,
          true,
          "Ninguno",
          "Caballo de tiro muy potente.",
          null),
      new CaravanBeastCatalogItem(
          "camello",
          "Camello",
          150,
          225,
          "G",
          4,
          50,
          -3,
          true,
          "Adaptado al calor",
          "Camello resistente para travesías cálidas.",
          null),
      new CaravanBeastCatalogItem(
          "mula",
          "Mula",
          8,
          null,
          "M",
          2,
          30,
          0,
          true,
          "Ninguno",
          "Animal de tiro resistente y económico.",
          null),
      new CaravanBeastCatalogItem(
          "buey",
          "Buey",
          50,
          null,
          "G",
          6,
          40,
          1,
          true,
          "Ninguno",
          "Animal fuerte, habitual en tareas de tiro.",
          null),
      new CaravanBeastCatalogItem(
          "yak",
          "Yak",
          100,
          null,
          "G",
          7,
          30,
          3,
          true,
          "Adaptado al frío",
          "Animal de tiro robusto para entornos fríos.",
          null),
      new CaravanBeastCatalogItem(
          "bisonte",
          "Bisonte",
          50,
          75,
          "G",
          8,
          40,
          1,
          true,
          "Ninguno",
          "Bestia poderosa para tiro pesado.",
          null),
      new CaravanBeastCatalogItem(
          "lagarto-monitor-gigante",
          "Lagarto monitor gigante",
          300,
          450,
          "E",
          3,
          30,
          -4,
          true,
          "Adaptado al calor",
          "Criatura exótica de gran tamaño.",
          null),
      new CaravanBeastCatalogItem(
          "grifo",
          "Grifo",
          null,
          8000,
          "G",
          3,
          30,
          null,
          true,
          "Criatura alada",
          "Bestia excepcional y muy costosa.",
          null),
      new CaravanBeastCatalogItem(
          "alce-gigante",
          "Alce gigante",
          200,
          300,
          "G",
          4,
          40,
          2,
          true,
          "Adaptado al frío",
          "Animal enorme y resistente.",
          null),
      new CaravanBeastCatalogItem(
          "perro-de-monta",
          "Perro de monta",
          null,
          150,
          "M",
          2,
          40,
          0,
          true,
          "Ninguno",
          "Perro entrenado para transporte montado.",
          null),
      new CaravanBeastCatalogItem(
          "perro-de-trineo",
          "Perro de trineo",
          150,
          200,
          "M",
          3,
          40,
          3,
          true,
          "Adaptado al frío",
          "Perro preparado para tirar de trineos.",
          null));

  private CaravanBeastCatalog() {}

  public static List<CaravanBeastCatalogItem> all() {
    return BEASTS;
  }

  public static Optional<CaravanBeastCatalogItem> findByCode(String code) {
    return BEASTS.stream().filter(item -> item.code().equals(code)).findFirst();
  }
}
