package com.gestioncaravana.domain;

import java.util.List;
import java.util.Optional;

public final class CargoCatalog {

  private static final List<CargoCatalogItem> ITEMS = List.of(
      new CargoCatalogItem(
          "estufa",
          "Estufa",
          "Artículos de mejora",
          "10 po",
          1,
          false,
          1,
          false,
          "Unidad",
          "Hasta 20 criaturas medianas o pequeñas duplican el efecto del carbón.",
          "Pequeña estufa portátil para la caravana.",
          null,
          List.of(),
          List.of()),
      new CargoCatalogItem(
          "altar-sagrado",
          "Altar Sagrado",
          "Artículos de mejora",
          "500 po",
          1,
          false,
          1,
          false,
          "Unidad",
          "Permite aprovechar la dote de caravana santificada.",
          "Altar consagrado a una deidad concreta.",
          null,
          List.of("deity"),
          List.of()),
      new CargoCatalogItem(
          "cocina-portatil",
          "Cocina Portátil",
          "Artículos de mejora",
          "500 po",
          1,
          false,
          1,
          false,
          "Unidad",
          "Un cocinero puede duplicar su rendimiento.",
          "Juego portátil de hornillos, ollas y utensilios.",
          null,
          List.of(),
          List.of()),
      new CargoCatalogItem(
          "equipo-para-climas-frios",
          "Equipo Para Climas Fríos",
          "Artículos de mejora",
          "200 po",
          1,
          false,
          1,
          false,
          "Unidad",
          "Evita penalizadores adicionales por frío extremo.",
          "Abrigos y herramientas para cruzar entornos fríos.",
          null,
          List.of(),
          List.of()),
      new CargoCatalogItem(
          "pabellon-de-entretenimiento",
          "Pabellón De Entretenimiento",
          "Artículos de mejora",
          "1 200 po",
          1,
          false,
          5,
          false,
          "Unidad",
          "Genera ingresos y aumenta la moral mientras está desplegado.",
          "Gran carpa para actuaciones y exposiciones.",
          null,
          List.of(),
          List.of()),
      new CargoCatalogItem(
          "piedra-de-comunicacion",
          "Piedra De Comunicación",
          "Artículos de mejora",
          "3 000 po",
          1,
          false,
          1,
          false,
          "Unidad",
          "Permite comunicarse a distancia entre vehículos.",
          "Piedra de enlace para la comunicación interna.",
          null,
          List.of(),
          List.of()),
      new CargoCatalogItem(
          "tenderete",
          "Tenderete",
          "Artículos de mejora",
          "250 po",
          1,
          false,
          2,
          false,
          "Unidad",
          "Mejora ligeramente las ganancias de la caravana.",
          "Puesto comercial plegable.",
          null,
          List.of(),
          List.of()),
      new CargoCatalogItem(
          "tienda-de-campana-de-supervivencia",
          "Tienda De Campaña De Supervivencia",
          "Artículos de mejora",
          "150 po",
          1,
          false,
          1,
          false,
          "Unidad",
          "Refugio temporal si se pierde un carro.",
          "Tienda para emergencias.",
          null,
          List.of(),
          List.of()),
      new CargoCatalogItem(
          "trampas-de-campamento",
          "Trampas De Campamento",
          "Artículos de mejora",
          "1 000 po",
          1,
          false,
          2,
          false,
          "Unidad",
          "Bonifica la Seguridad al acampar.",
          "Trampas portátiles para defensa del campamento.",
          null,
          List.of(),
          List.of()),
      new CargoCatalogItem(
          "carbon",
          "Carbón",
          "Artículos de mercancía",
          "1 po",
          1,
          false,
          1,
          false,
          "Unidad",
          "Sirve para calentarse durante el viaje.",
          "Combustible básico.",
          null,
          List.of(),
          List.of()),
      new CargoCatalogItem(
          "hielo",
          "Hielo",
          "Artículos de mercancía",
          "1 po",
          1,
          false,
          1,
          false,
          "Unidad",
          "Sirve para enfriarse o conservar suministros perecederos.",
          "Bloques de hielo transportables.",
          null,
          List.of(),
          List.of()),
      new CargoCatalogItem(
          "lena",
          "Leña",
          "Artículos de mercancía",
          "5 pp",
          1,
          false,
          1,
          false,
          "Unidad",
          "Funciona como carbón, pero con peor eficiencia.",
          "Leña seca transportable.",
          null,
          List.of(),
          List.of()),
      new CargoCatalogItem(
          "material-de-reparaciones",
          "Material De Reparaciones",
          "Artículos de mercancía",
          "25 po",
          1,
          false,
          1,
          false,
          "Unidad",
          "Permite reparar carros dañados.",
          "Madera, clavos y otros repuestos.",
          null,
          List.of(),
          List.of()),
      new CargoCatalogItem(
          "mercancias",
          "Mercancías",
          "Artículos de mercancía",
          "10 po",
          1,
          false,
          1,
          false,
          "Unidad",
          "Bienes genéricos para vender en asentamientos.",
          "Metales, telas, especias y similares.",
          null,
          List.of(),
          List.of()),
      new CargoCatalogItem(
          "mercancias-especificas",
          "Mercancías Específicas",
          "Artículos de mercancía",
          "Variable",
          1,
          false,
          1,
          false,
          "Unidad",
          "Representan un tipo concreto de mercancía.",
          "Mercancía especializada elegida al adquirirla.",
          null,
          List.of("specificCommodity"),
          List.of()),
      new CargoCatalogItem(
          "materiales-magicos-diversos",
          "Materiales Mágicos Diversos",
          "Artículos de mercancía",
          "25 000 po",
          1,
          false,
          1,
          false,
          "Unidad",
          "Componentes de conjuro y material arcano.",
          "Volumen medio de materiales mágicos.",
          null,
          List.of(),
          List.of()),
      new CargoCatalogItem(
          "mercancias-locales",
          "Mercancías Locales",
          "Artículos de mercancía",
          "20 po",
          1,
          false,
          1,
          false,
          "Unidad",
          "Se valoran más cuanto más lejos viajan.",
          "Mercancía con origen asociado.",
          null,
          List.of("origin"),
          List.of()),
      new CargoCatalogItem(
          "suministros",
          "Suministros",
          "Artículos de mercancía",
          "5 po",
          1,
          false,
          1,
          false,
          "Unidad",
          "Equivale a 10 unidades de provisiones.",
          "Raciones y agua potable.",
          null,
          List.of(),
          List.of("carro-de-suministros")),
      new CargoCatalogItem(
          "suministros-perecederos",
          "Suministros Perecederos",
          "Artículos de mercancía",
          "1 po",
          1,
          false,
          1,
          false,
          "Unidad",
          "Se deterioran con el paso de los días.",
          "Provisiones delicadas.",
          null,
          List.of(),
          List.of("carro-de-suministros")),
      new CargoCatalogItem(
          "tesoro",
          "Tesoro",
          "Artículos de mercancía",
          "Variable",
          1,
          true,
          1,
          true,
          "Libras",
          "Cualquier objeto de valor que el grupo quiera transportar.",
          "Reserva de monedas, gemas y botín.",
          "50 libras ocupan 1 unidad de cargamento.",
          List.of(),
          List.of()),
      new CargoCatalogItem(
          "municion-de-balista",
          "Munición De Balista",
          "Munición",
          "1 po",
          20,
          false,
          1,
          false,
          "Paquete",
          "Amunición estándar para balistas.",
          "Bolsa de veinte virotes.",
          null,
          List.of(),
          List.of()),
      new CargoCatalogItem(
          "municion-perforadora-de-balista",
          "Munición Perforadora De Balista",
          "Munición",
          "2 po",
          10,
          false,
          1,
          false,
          "Paquete",
          "Ignora parte de la dureza o reducción de daño.",
          "Virotes perforadores especiales.",
          null,
          List.of(),
          List.of()),
      new CargoCatalogItem(
          "municion-de-canon",
          "Munición De Cañón",
          "Munición",
          "1 po",
          100,
          false,
          1,
          false,
          "Paquete",
          "Proyectiles para cañón.",
          "Munición pesada de artillería.",
          null,
          List.of(),
          List.of()),
      new CargoCatalogItem(
          "municion-de-draco-de-fuego",
          "Munición De Draco De Fuego",
          "Munición",
          "5 po",
          20,
          false,
          1,
          false,
          "Paquete",
          "Munición especial para el draco de fuego.",
          "Carga explosiva o ígnea.",
          null,
          List.of(),
          List.of()));

  private CargoCatalog() {}

  public static List<CargoCatalogItem> all() {
    return ITEMS;
  }

  public static Optional<CargoCatalogItem> findByCode(String code) {
    return ITEMS.stream().filter(item -> item.code().equals(code)).findFirst();
  }
}
