package com.gestioncaravana.domain;

import java.util.List;
import java.util.Optional;

public final class WagonImprovementCatalog {

  private static final List<WagonImprovementType> IMPROVEMENTS = List.of(
      new WagonImprovementType(
          "acorazado",
          "Acorazado",
          "Defensa",
          "x10",
          null,
          1.5,
          5,
          null,
          "Aumenta la resistencia general del carro.",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          false,
          null,
          List.of(),
          List.of(),
          "Aumenta en 1 cualquier beneficio derivado de la presencia del carro en la caravana.",
          "El carro se vuelve más resistente a costa de perder movilidad.",
          null),
      new WagonImprovementType(
          "refuerzo-para-carros",
          "Refuerzo Para Carros",
          "Defensa",
          "500 po",
          10,
          null,
          null,
          null,
          "Aumenta los puntos de golpe del carro.",
          null,
          null,
          null,
          null,
          -1,
          null,
          null,
          null,
          null,
          1,
          false,
          null,
          List.of(),
          List.of(),
          "Aumenta en 10 los puntos de golpe del carro.",
          "Estos puntales, placas y soportes refuerzan el carro.",
          null),
      new WagonImprovementType(
          "heraldica",
          "Heráldica",
          "Utilidad",
          "x0.5",
          null,
          null,
          null,
          null,
          "Convierte al carro en un emblema visible para toda la caravana.",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          false,
          null,
          List.of(),
          List.of(),
          "Si todos los carros tienen esta mejora, aumenta en 2 la moral máxima de la caravana.",
          "Mejora heráldica y simbólica.",
          null),
      new WagonImprovementType(
          "iluminacion-magica",
          "Iluminación Mágica",
          "Utilidad",
          "600 po",
          null,
          null,
          null,
          null,
          "Emite una luz mágica constante.",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          false,
          null,
          List.of(),
          List.of(),
          "El carro emite una luz mágica constante a 60'.",
          "Puedes reducir su coste con antorchas siempreardientes.",
          null),
      new WagonImprovementType(
          "espacio-extendido-viajeros",
          "Espacio Extendido (viajeros)",
          "Capacidad",
          "2 000 po",
          null,
          null,
          null,
          null,
          "Aumenta la capacidad de viajeros.",
          null,
          1.25,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          999,
          true,
          null,
          List.of(),
          List.of(),
          "Aumenta un 25% la capacidad de viajeros del carro, como mínimo 1.",
          "Puede aplicarse varias veces al mismo carro.",
          null),
      new WagonImprovementType(
          "espacio-extendido-cargamento",
          "Espacio Extendido (cargamento)",
          "Capacidad",
          "2 000 po",
          null,
          null,
          null,
          null,
          "Aumenta la capacidad de cargamento.",
          null,
          null,
          null,
          null,
          null,
          1.25,
          2,
          null,
          null,
          999,
          true,
          null,
          List.of(),
          List.of(),
          "Aumenta un 25% la capacidad de cargamento del carro, como mínimo 2.",
          "Puede aplicarse varias veces al mismo carro.",
          null),
      new WagonImprovementType(
          "aislamiento-para-el-frio",
          "Aislamiento Para El Frío",
          "Clima",
          "x2",
          null,
          null,
          2,
          null,
          "Reduce el impacto del frío.",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          false,
          null,
          List.of(),
          List.of(),
          "Cuenta la temperatura como si fuese 20 °F más alta para los viajeros del carro.",
          "Reduce la velocidad de la caravana cuando al menos un carro tenga este aislamiento.",
          null),
      new WagonImprovementType(
          "aislamiento-para-el-calor",
          "Aislamiento Para El Calor",
          "Clima",
          "x2",
          null,
          null,
          2,
          null,
          "Reduce el impacto del calor.",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          false,
          null,
          List.of(),
          List.of(),
          "Cuenta la temperatura como si fuese 20 °F más baja para los viajeros del carro.",
          "Reduce la velocidad de la caravana cuando este aislamiento está presente.",
          null),
      new WagonImprovementType(
          "nevera",
          "Nevera",
          "Clima",
          "x2",
          null,
          null,
          2,
          null,
          "Preserva suministros perecederos.",
          null,
          null,
          null,
          0,
          null,
          null,
          null,
          null,
          null,
          1,
          false,
          null,
          List.of(),
          List.of(),
          "Los suministros perecederos tardan un día más en perder efectividad.",
          "Ningún viajero puede pasar la noche en este carro.",
          null),
      new WagonImprovementType(
          "patines-de-hielo",
          "Patines De Hielo",
          "Movimiento",
          "x1/10",
          null,
          null,
          null,
          null,
          "Modifica la propulsión en terreno helado.",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          false,
          null,
          List.of(),
          List.of("ruedas-mejoradas"),
          "Disminuye a la mitad la propulsión necesaria en hielo y la cuadruplica en terreno no helado.",
          "No es compatible con la mejora de ruedas.",
          null),
      new WagonImprovementType(
          "balista-ligera",
          "Balista Ligera",
          "Armamento",
          "500 po",
          null,
          null,
          null,
          null,
          "Añade una balista ligera.",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          false,
          null,
          List.of(),
          List.of(),
          "Un viajero puede manejar la balista ligera.",
          "Arma montada en el carro.",
          null),
      new WagonImprovementType(
          "balista-pesada",
          "Balista Pesada",
          "Armamento",
          "500 po",
          null,
          null,
          null,
          null,
          "Añade una balista pesada.",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          false,
          null,
          List.of(),
          List.of(),
          "Tres viajeros pueden disparar la balista pesada.",
          "Arma montada en el carro.",
          null),
      new WagonImprovementType(
          "canon",
          "Cañón",
          "Armamento",
          "6 000 po",
          null,
          null,
          null,
          null,
          "Añade un cañón.",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          false,
          null,
          List.of(),
          List.of(),
          "Dos viajeros pueden manejar el cañón.",
          "Arma montada en el carro.",
          null),
      new WagonImprovementType(
          "canon-boca-demoniaca",
          "Cañón Boca Demoniaca",
          "Armamento",
          "9 000 po",
          null,
          null,
          null,
          null,
          "Añade un cañón boca demoniaca.",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          false,
          null,
          List.of(),
          List.of(),
          "Dos viajeros pueden manejar el cañón.",
          "Arma montada en el carro.",
          null),
      new WagonImprovementType(
          "fuego-de-draco",
          "Fuego De Draco",
          "Armamento",
          "4 000 po",
          null,
          null,
          null,
          null,
          "Añade fuego de draco.",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          false,
          null,
          List.of(),
          List.of(),
          "Dos viajeros pueden manejar el fuego de draco.",
          "Arma montada en el carro.",
          null),
      new WagonImprovementType(
          "ruedas-mejoradas",
          "Ruedas Mejoradas",
          "Movimiento",
          "500 po",
          null,
          null,
          null,
          null,
          "Mejora la velocidad de la caravana.",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          false,
          null,
          List.of(),
          List.of("patines-de-hielo"),
          "Si todos los carros tienen esta mejora, aumenta la velocidad de la caravana en 8 millas al día.",
          "Combinación de refuerzos para las ruedas y ejes magistralmente diseñados.",
          null),
      new WagonImprovementType(
          "tiro-de-dos-caballos",
          "Tiro De Dos Caballos",
          "Propulsión",
          "20 po",
          null,
          null,
          null,
          null,
          "+1 criatura grande / +4 medianas (+5 Fuerza)",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          1,
          false,
          "1 Criatura grande / 4 medianas",
          List.of(),
          List.of(),
          "-",
          "Aumenta la propulsión del carro.",
          null),
      new WagonImprovementType(
          "tiro-de-cuatro-caballos",
          "Tiro De Cuatro Caballos",
          "Propulsión",
          "100 po",
          5,
          null,
          null,
          null,
          "+2 criatura grande / +8 medianas (+10 Fuerza)",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          2,
          1,
          false,
          "2 Criatura grande / 8 medianas",
          List.of("tiro-de-dos-caballos"),
          List.of(),
          "Si todos los carros tienen esta mejora, aumenta la velocidad de la caravana en 4 millas al día.",
          "Aumenta el tiro y los puntos de golpe.",
          null),
      new WagonImprovementType(
          "tiro-de-seis-caballos",
          "Tiro De Seis Caballos",
          "Propulsión",
          "150 po",
          5,
          null,
          null,
          null,
          "+2 criatura grande / +8 medianas (+10 Fuerza)",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          2,
          1,
          false,
          null,
          List.of("tiro-de-cuatro-caballos"),
          List.of(),
          "Si todos los carros tienen esta mejora, aumenta la velocidad de la caravana en 4 millas al día.",
          "Aumenta el tiro y los puntos de golpe.",
          null),
      new WagonImprovementType(
          "tiro-de-ocho-caballos",
          "Tiro De Ocho Caballos",
          "Propulsión",
          "200 po",
          5,
          null,
          null,
          null,
          "+2 criatura grande / +8 medianas (+10 Fuerza)",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          2,
          1,
          false,
          null,
          List.of("tiro-de-seis-caballos"),
          List.of(),
          "Si todos los carros tienen esta mejora, aumenta la velocidad de la caravana en 4 millas al día.",
          "Aumenta el tiro y los puntos de golpe.",
          null));

  private WagonImprovementCatalog() {}

  public static List<WagonImprovementType> all() {
    return IMPROVEMENTS;
  }

  public static Optional<WagonImprovementType> findByCode(String code) {
    return IMPROVEMENTS.stream().filter(type -> type.code().equals(code)).findFirst();
  }
}
