package com.gestioncaravana.domain;

import java.util.List;
import java.util.Optional;

public final class WagonCatalog {

  private static final List<WagonType> WAGONS = List.of(
      new WagonType(
          "carro-cubierto",
          "Carro Cubierto",
          "Viajeros",
          150,
          30,
          5,
          "1 Criatura grande / 4 medianas (+4 Fuerza)",
          8,
          4,
          WagonLimit.unlimited("Ninguno"),
          2,
          "Ninguno",
          "Los carros cubiertos proporcionan a los viajeros un lugar cómodo, aunque básico donde resguardarse, tanto durante el trayecto como cuando se detiene a hacer noche en mitad de la nada. Las paredes y el techo son fundamentalmente tela.",
          null),
      new WagonType(
          "carro-de-viajeros",
          "Carro De Viajeros",
          "Viajeros",
          200,
          60,
          5,
          "2 Criatura grande / 8 medianas (+10 Fuerza)",
          8,
          4,
          WagonLimit.unlimited("Ninguno"),
          2,
          "+1 CA de la caravana",
          "Los carros de viajeros hacen la misma función que los carros cubiertos: proporcional un lugar donde resguardarse. Pero este tiene laterales más resistentes y un techo sólido. El habitáculo es entero de madera.",
          null),
      new WagonType(
          "carro-de-esclavista",
          "Carro De Esclavista",
          "Viajeros",
          150,
          30,
          5,
          "1 Criatura grande / 4 medianas (+5 Fuerza)",
          16,
          2,
          WagonLimit.fixed(2, "2"),
          2,
          "Ninguno",
          "Un carro de madera preparado para transportar hasta dieciseis esclavos en unas condiciones infrahumanas suficientes para mantenerlos con vida.",
          "Los viajeros asignados a este carro sólo pueden ejercer el rol de esclavo."),
      new WagonType(
          "carro-de-prisioneros",
          "Carro De Prisioneros",
          "Viajeros",
          300,
          60,
          5,
          "1 Criatura grande / 4 medianas (+5 Fuerza)",
          10,
          2,
          WagonLimit.fixed(2, "2"),
          2,
          "+2 a la Seguridad de la caravana.",
          "Un carro de madera preparado para transportar hasta diez presos en unas condiciones similares",
          "Los viajeros asignados a este carro sólo pueden ejercer el rol de prisionero."),
      new WagonType(
          "carro-zoologico",
          "Carro Zoológico",
          "Viajeros",
          175,
          60,
          5,
          "1 Criatura grande / 4 medianas (+5 Fuerza)",
          10,
          2,
          WagonLimit.fixed(2, "2"),
          2,
          "Ninguno.",
          "Un carro de madera preparado para transportar diversos animales en su interior de forma cómoda.",
          "Los viajeros asignados a este carro no pueden ser humanoides."),
      new WagonType(
          "carruaje-comodo",
          "Carruaje Cómodo",
          "Viajeros",
          250,
          60,
          5,
          "1 Criatura grande / 4 medianas (+6 Fuerza)",
          4,
          4,
          WagonLimit.unlimited("Ninguno"),
          1,
          "Ninguno",
          "Este carruaje está pensado para permitir un viaje cómodo así como pasar la noche de forma agradable.",
          null),
      new WagonType(
          "carruaje-familiar",
          "Carruaje Familiar",
          "Viajeros",
          150,
          60,
          5,
          "2 Criatura grande / 8 medianas (+10 Fuerza)",
          6,
          4,
          WagonLimit.ratio(5, "1/5 de la Caravana"),
          2,
          "Ninguno",
          "Este carruaje está pensado para permitir el viaje a dos unidades familiares, permitiendo que las criaturas pequeñas cuenten como ½ tripulante de cara a la capacidad de viajeros.",
          null),
      new WagonType(
          "carruaje-real",
          "Carruaje Real",
          "Viajeros",
          775,
          80,
          5,
          "2 Criatura grande / 8 medianas (+8 Fuerza)",
          3,
          2,
          WagonLimit.fixed(1, "1"),
          2,
          "+2 a la determinación por cada viajero ejerciendo el rol de “pasajero” que esté asignado a este carromato.",
          "Este hermoso carruaje sube los ánimos de la caravana entera, siempre que los tripulantes tengan una buena relación entre ellos.",
          null),
      new WagonType(
          "trineo-de-pasajeros",
          "Trineo De Pasajeros",
          "Viajeros",
          10,
          10,
          3,
          "2 medianas (+4 Fuerza)",
          2,
          1,
          WagonLimit.unlimited("Ninguno"),
          2,
          "Ninguno",
          "Un trineo tirado por uno o dos perros no es el lugar más cómodo para viajar, pero es posiblemente el medio de transporte más barato para cruzar parajes helados.",
          null),
      new WagonType(
          "trineo-de-carga",
          "Trineo De Carga",
          "Carga",
          10,
          10,
          3,
          "2 medianas (+4 Fuerza)",
          1,
          2,
          WagonLimit.unlimited("Ninguno"),
          2,
          "Ninguno",
          "Un trineo tirado por uno o dos perros no es el lugar más cómodo para viajar, pero es posiblemente el medio de transporte más barato para cruzar parajes helados.",
          null),
      new WagonType(
          "carro-biblioteca",
          "Carro Biblioteca",
          "Especiales",
          500,
          40,
          5,
          "2 Criatura grande / 8 medianas (+9 Fuerza)",
          1,
          4,
          WagonLimit.fixed(1, "1"),
          2,
          "Mientras este carro transporte al menos una unidad de carga el libros de investigación variados sobre un tema, aporta un +4 a cualquier tirada de saber realizda por cualquier viajero que esté investigando dentro de este carro.",
          "Este carro es similar a un carro de suministros por fuera, pero el interior está distribuido en estanterías y mesas de estudio para poder llevar a cabo investigaciones utilizando el material que transporte.",
          null),
      new WagonType(
          "carro-descubierto",
          "Carro Descubierto",
          "Carga",
          150,
          20,
          5,
          "1 Criatura grande / 4 medianas (+4 Fuerza)",
          0,
          10,
          WagonLimit.unlimited("Ninguno"),
          1,
          "Cada día con inclemencias del tiempo, cada carga tiene un 5% de probabilidades de echarse a perder. Esta probabilidad puede aumentar ante inclemencias más graves.",
          "Estos carros básicos permiten transportar cargamento, pero no los protege de las inclemencias del tiempo ni es un lugar aceptable para descansar.",
          null),
      new WagonType(
          "carro-de-mercancias",
          "Carro De Mercancías",
          "Carga",
          200,
          60,
          5,
          "2 Criatura grande / 8 medianas (+10 Fuerza)",
          1,
          10,
          WagonLimit.unlimited("Ninguno"),
          1,
          "Ninguno",
          "Estos carros están diseñados para transportar cargamento en lugar de viajeros, aunque sirven de lugar improvisado para que un viajero pase la noche.",
          null),
      new WagonType(
          "carro-de-mercancias-especificas",
          "Carro De Mercancías Específicas",
          "Carga",
          300,
          60,
          5,
          "2 Criatura grande / 8 medianas (+10 Fuerza)",
          1,
          20,
          WagonLimit.unlimited("Ninguno"),
          1,
          "Ninguno",
          "Estos carros están diseñados para transportar cargamento en particular. Tan solo puede portarse un mismo tipo de mercancías específica. La mercancía debe ser decidida en el momento de adquisición del carro y no puede cambiarse.",
          null),
      new WagonType(
          "carro-de-suministros",
          "Carro De Suministros",
          "Carga",
          300,
          60,
          5,
          "2 Criatura grande / 8 medianas (+10 Fuerza)",
          1,
          20,
          WagonLimit.unlimited("Ninguno"),
          1,
          "Ninguno",
          "Estos carros están diseñados para transportar distintos víveres y un depósito de agua potable. Tan solo puede transportar suministros y suministros perecederos.",
          null),
      new WagonType(
          "carro-museo",
          "Carro Museo",
          "Especiales",
          350,
          60,
          5,
          "1 Criatura grande / 4 medianas (+5 Fuerza)",
          1,
          6,
          WagonLimit.fixed(1, "1"),
          1,
          "Al estar en un asentamiento descansando o parado, este carro recibe visitantes que pagan por ver las maravillas que esconde. Cada día en estas condiciones, la caravana recibe un 1% del precio de los tesoros que lleve y que sean obras de arte, objetos valiosos o equipamiento de gran calidad. Como máximo puedes recibir al día un 1% del valor base del asentamiento (2% si está signado un animador itinerante).",
          "Un carro de madera en el que exponer los tesoros que la caravana haya conseguido, así como narrar sus hazañas para que la gente de los distintos asentamientos pague por verlo.",
          "La capacidad de cargamento de este carro solo puede utilizarse para cargar tesoro."),
      new WagonType(
          "carro-arcano",
          "Carro Arcano",
          "Especiales",
          500,
          50,
          5,
          "2 Criatura grande / 8 medianas (+8 Fuerza)",
          2,
          2,
          WagonLimit.fixed(1, "1"),
          2,
          "Los lanzadores de conjuros que usen este carro pueden reducir el coste de componentes materiales de hasta 10 po por conjuro. Una vez al día, cada lanzador de conjuros puede realizar una tirada de concentración con un bonificador de +4 para evitar la pérdida de un conjuro lanzando dentro de este carro.",
          "Este carro está imbuido con magia y cargado de diversos componentes mágicos que mejoran el uso de magia en su interior.",
          null),
      new WagonType(
          "carro-de-adivino",
          "Carro De Adivino",
          "Especiales",
          400,
          60,
          5,
          "1 Criatura grande / 4 medianas (+5 Fuerza)",
          1,
          4,
          WagonLimit.fixed(1, "1"),
          1,
          "Permite los beneficios de un adivino",
          "Este carro es similar a un carro cubierto, pero adaptado a medida para alojar al guía espiritual de una caravana: su adivino. El rol de adivino no está disponible sin este carro.",
          null),
      new WagonType(
          "carro-con-taller",
          "Carro Con Taller",
          "Especiales",
          500,
          60,
          5,
          "2 Criatura grande / 8 medianas (+8 Fuerza)",
          2,
          4,
          WagonLimit.unlimited("Ninguno"),
          1,
          "Permite que un artesano realice pruebas de artesanía durante el viaje como si no estuviese viajando o de aventuras.",
          "Este carro es similar a un carro cubierto, pero adaptado a medida para servir hasta a dos artesanos. Puede añadirse al carro equipamiento de artesano para ayudarle a sus pruebas de artesanía.",
          null),
      new WagonType(
          "carro-escuela",
          "Carro Escuela",
          "Especiales",
          375,
          60,
          5,
          "2 Criatura grande / 8 medianas (+8 Fuerza)",
          2,
          4,
          WagonLimit.fixed(1, "1"),
          2,
          "Permite hasta a 2 viajeros ejercer el rol de profesor.",
          "Pensado inicialmente para los niños y jóvenes que acompañan las caravanas, al final se termina usando por muchos más miembros de la caravana para adquirir conocimiento que nunca habían tenido ocasión de aprender.",
          null),
      new WagonType(
          "carro-huerto",
          "Carro Huerto",
          "Especiales",
          300,
          60,
          5,
          "2 Criatura grande / 8 medianas (+10 Fuerza)",
          2,
          1,
          WagonLimit.unlimited("Ninguno"),
          1,
          "Solo los viajeros asignados a este carro pueden ejercer el cargo de agricultor",
          "Un carro de madera con jardineras en el interior y un pequeño espacio habitable, preparado para que se puedan cultivar plantas comestibles.",
          null),
      new WagonType(
          "carro-medico",
          "Carro Médico",
          "Especiales",
          300,
          40,
          5,
          "2 Criatura grande / 8 medianas (+10 Fuerza)",
          6,
          1,
          WagonLimit.unlimited("Ninguno"),
          2,
          "Los viajeros con el cargo de pasajero asignados a este carro, duplican el beneficio de los cuidados médicos a largo plazo que reciban.",
          "Un carro de madera preparado para atender los problemas de salud del resto de la caravana.",
          null),
      new WagonType(
          "carro-vacio",
          "Carro Vacío",
          "Especiales",
          200,
          60,
          5,
          "2 Criatura grande / 8 medianas (+10 Fuerza)",
          3,
          5,
          WagonLimit.unlimited("Ninguno"),
          2,
          "Ninguno",
          "Los viajeros son muy imaginativos, y a menudo necesitan carros vacíos para llenar con sus propias ideas totalmente únicas. Estos carros están vacíos, y no están preparados ni para que la gente descanse en ellos ni para transportar suministros de forma segura. Por ejemplo una caravana podría querer crear una taberna en un carro.",
          null));

  private WagonCatalog() {}

  public static List<WagonType> all() {
    return WAGONS;
  }

  public static Optional<WagonType> findByCode(String code) {
    return WAGONS.stream().filter(wagonType -> wagonType.code().equals(code)).findFirst();
  }
}
